增加对rate可选范围边界的控制,修改后整个比例范围为[start_rate,end_rate],默认为[0,99],以支持用户根据精度模型进行个性化定制;修改对收益与否的判断,将之前的判断方式进行了进一步的完善,一方面将收益的判断的边界设置成了-1微秒,此外也对判断过程进行了修改,通过其曲线的类型进行了判断,以尽可能支持一些profiling波动导致的错误,容错更好了一些.

diff --git a/lnlamp b/lnlamp
--- a/lnlamp
+++ b/lnlamp
@@ -35,6 +35,8 @@ timing_type=0
 input="input.txt"
 # TODO: 添加profiling时的混合比例 (-r|--rate)  的设置
 rate_array=(1 12 25 37 50 62 75 87 99)
+start_rate=0
+end_rate=99
 # rate_array=(16 32 49 66 82)
 # TODO: 完善下面 Profiling时编译的一些参数的自定义设置(CC已经实现根据后缀名字自动确定)
 VERBOSE=""
@@ -1472,22 +1474,27 @@ time_profiling=$((($end-$start)/1000000)) # 毫秒
 start=`date +%s%N`
 # 3.1 先确定最合适的Rate的可能取值
 best_rate=()
+amp_type=-2
 # 如果开口向下且对称轴小于0、或者开头向上且对称轴大于99,那么就是收益模型单调下降.
-if ([ $(echo "$extremeValue < 0" | bc) -eq 1 ] && [ $(echo "$equ_a < 0" | bc) -eq 1 ]) || ([ $(echo "$extremeValue > 99" | bc) -eq 1 ] && [ $(echo "$equ_a > 0" | bc) -eq 1 ]);
+if ([ $(echo "$extremeValue < $start_rate" | bc) -eq 1 ] && [ $(echo "$equ_a < 0" | bc) -eq 1 ]) || ([ $(echo "$extremeValue > $end_rate" | bc) -eq 1 ] && [ $(echo "$equ_a > 0" | bc) -eq 1 ]);
 then
-    best_rate+=( 0 )
+    best_rate+=( $start_rate )
+    amp_type=1
 # 如果开口向下且对称轴大于99、或者开头向上且对称轴小于0,那么就是收益模型单调上升.
-elif ([ $(echo "$extremeValue > 99" | bc) -eq 1 ] && [ $(echo "$equ_a < 0" | bc) -eq 1 ]) || ([ $(echo "$extremeValue < 0" | bc) -eq 1 ] && [ $(echo "$equ_a > 0" | bc) -eq 1 ]);
+elif ([ $(echo "$extremeValue > $end_rate" | bc) -eq 1 ] && [ $(echo "$equ_a < 0" | bc) -eq 1 ]) || ([ $(echo "$extremeValue < $start_rate" | bc) -eq 1 ] && [ $(echo "$equ_a > 0" | bc) -eq 1 ]);
 then
-    best_rate+=( 99 )
+    best_rate+=( $end_rate )
+    amp_type=2
 # 如果对称轴介于0和99中间,且开头是向下的话,那么对称轴附近的比例值就是结果
 elif [ $(echo "$equ_a < 0" | bc) -eq 1 ];
 then
     best_rate+=( $(echo $extremeValue | cut -d '.' -f1) );
-# 如果对称轴介于0和99中间,且开头是向上的话,那么同样也不适合做混合精度.
+    amp_type=0
+# 如果对称轴介于0和99中间,且开头是向上的话,那么边界的比例值就是结果.
 else
-    best_rate+=( 0 )
-    best_rate+=( 99 )
+    best_rate+=( $start_rate )
+    best_rate+=( $end_rate )
+    amp_type=-1
 fi
 # 3.2 对可能的取值做预测(推理) [也可以做Profiling(注释掉的代码部分)]
 best_incomes=()
@@ -1519,46 +1526,57 @@ fi
 
 
 # Step4: 打印最终结果.
-if [ ${#best_incomes[@]} -eq 1 ];
+# 设置是否有收益的边界为-1微秒
+bound_earnings=-0.000001
+# 如果是单调上升的情况
+if [ ${amp_type} -eq 2 ];
 then
-    if [ $(echo "${best_incomes[@]} > 0.0" | bc) -eq 1 ];
-    then 
-        # 如果是单调下降
-        if [ ${best_rate[@]} -eq 0 ];
-        then
-            echo "The performance of the lnlamp programs decreases monotonically with increasing Rate, so the Rate 0 is the best. "
-            # 生成最合适比例下对应的混合精度代码提供给用户
-            ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
-            if [ $? -ne 0 ]; then
-                echo "lnlamp: error: PPCG Codegen meets errors at the end."
-                echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}."
-                exit
-            fi
-            echo "Now, We have automatically generated a mixed precision program (${target_file})at this Ratio(${best_rate[@]}). "
-        # 如果是单调上升
-        elif [ ${best_rate[@]} -eq 99 ];
-        then
-            echo "The performance of the lnlamp program rises monotonically with increasing Rate, so the Rate 99 is the best. "
-            # 生成最合适比例下对应的混合精度代码提供给用户
-            ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
-            if [ $? -ne 0 ]; then
-                echo "lnlamp: error: PPCG Codegen meets errors at the end."
-                echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}."
-                exit
-            fi
-            echo "Now, We have automatically generated a mixed precision program (${target_file})at this Ratio(${best_rate[@]}). "
-        # 如果是二次关系
-        else
-            echo "The performance of the lnlamp program shows a quadratic relationship with the Rate, so the integer value around Rate ($extremeValue) is probably the most appropriate ratio. "
-            # 生成最合适比例下对应的混合精度代码提供给用户
-            ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
-            if [ $? -ne 0 ]; then
-                echo "lnlamp: error: PPCG Codegen meets errors at the end."
-                echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}."
-                exit
-            fi
-            echo "Now, We have automatically generated a mixed precision program (${target_file})at this Ratio(${best_rate[@]}). "
+    echo "Unfortunately, we did not find the most suitable mixed precision Rate for this program. So the original program is probably the best. "
+    # 生成没有进行混合精度，但是PPCG优化后的代码提供给用户
+    ppcg --target c --no-automatic-mixed-precision ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "lnlamp: error: PPCG Codegen meets errors at the end."
+        echo "lnlamp: error: ppcg --target c --no-automatic-mixed-precision ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}."
+        exit
+    fi
+    echo "Now, We have automatically generated a program (${target_file}) with PPCG for you. "
+
+    # 临时加一个语句，生成schedule+mix的版本
+    ppcg --target c --no-automatic-mixed-precision ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}.no-tile.c > /dev/null 2>&1
+    # 临时加一个语句，生成只进行mix的版本
+    ppcg --target c --no-automatic-mixed-precision --no-reschedule $src_args -o ${target_file}.only-mix.c > /dev/null 2>&1  
+# 如果是单调下降的情况
+elif [ ${amp_type} -eq 1 ];
+then
+    echo "The performance of the lnlamp programs decreases monotonically with increasing Rate, so the Rate $start_rate is the best. "
+    # 生成最合适比例下对应的混合精度代码提供给用户
+    ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "lnlamp: error: PPCG Codegen meets errors at the end."
+        echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}."
+        exit
+    fi
+    echo "Now, We have automatically generated a mixed precision program (${target_file})at this Ratio(${best_rate[@]}). "
+    
+    # 临时加一个语句，生成schedule+mix的版本
+    ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}.no-tile.c > /dev/null 2>&1
+    # 临时加一个语句，生成只进行mix的版本
+    ppcg --target c -R ${best_rate[@]} --no-reschedule $src_args -o ${target_file}.only-mix.c > /dev/null 2>&1
+# 如果是二次抛物线，开口向下的情况
+elif [ ${amp_type} -eq 0 ];
+then
+    if [ $(echo "${best_incomes[@]} > ${bound_earnings}" | bc) -eq 1 ];
+    then
+        echo "The performance of the lnlamp program shows an open-down quadratic relationship with Rate, so the integer value around Rate($extremeValue) is probably the most appropriate ratio. "
+        # 生成最合适比例下对应的混合精度代码提供给用户
+        ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "lnlamp: error: PPCG Codegen meets errors at the end."
+            echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}."
+            exit
         fi
+        echo "Now, We have automatically generated a mixed precision program (${target_file})at this Ratio(${best_rate[@]}). "
+        
         # 临时加一个语句，生成schedule+mix的版本
         ppcg --target c -R ${best_rate[@]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}.no-tile.c > /dev/null 2>&1
         # 临时加一个语句，生成只进行mix的版本
@@ -1573,13 +1591,16 @@ then
             exit
         fi
         echo "Now, We have automatically generated a program (${target_file}) with PPCG for you. "
+        
         # 临时加一个语句，生成schedule+mix的版本
         ppcg --target c --no-automatic-mixed-precision ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}.no-tile.c > /dev/null 2>&1
         # 临时加一个语句，生成只进行mix的版本
         ppcg --target c --no-automatic-mixed-precision --no-reschedule $src_args -o ${target_file}.only-mix.c > /dev/null 2>&1
     fi
-else
-    max_income=0.0
+# 如果是二次抛物线，开口向上的情况
+elif [ ${amp_type} -eq -1 ];
+then
+    max_income=-60
     max_income_id=-1.0
     # 确定一下最大收益及其对应的下标
     for ((i=0;i<${#best_incomes[@]};i++));
@@ -1591,9 +1612,9 @@ else
         fi
     done
     # 根据最大收益,确定适不适合做混合精度
-    if [ $(echo "${max_income} > 0.0" | bc) -eq 1 ];
+    if [ $(echo "${max_income} > ${bound_earnings}" | bc) -eq 1 ];
     then
-        echo "The performance of the lnlamp program shows a quadratic relationship with the Rate, so the integer value around Rate (${best_rate[$max_income_id]}) is probably the most appropriate ratio. "  
+        echo "The performance of the lnlamp program shows an open-upward quadratic curve relationship with Rate, so the integer value around Rate (${best_rate[$max_income_id]}) is probably the most appropriate ratio. "  
         # 生成最合适比例下对应的混合精度代码提供给用户
         ppcg --target c -R ${best_rate[$max_income_id]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_TILE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file} > /dev/null 2>&1
         if [ $? -ne 0 ]; then
@@ -1602,6 +1623,7 @@ else
             exit
         fi
         echo "Now, We have automatically generated a mixed precision program (${target_file})at this Ratio(${best_rate[$max_income_id]}). "
+        
         # 临时加一个语句，生成schedule+mix的版本
         ppcg --target c -R ${best_rate[$max_income_id]} ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}.no-tile.c > /dev/null 2>&1
         # 临时加一个语句，生成只进行mix的版本
@@ -1616,11 +1638,14 @@ else
             exit
         fi
         echo "Now, We have automatically generated a program (${target_file}) with PPCG for you. "
+        
         # 临时加一个语句，生成schedule+mix的版本
         ppcg --target c --no-automatic-mixed-precision ${PPCG_ISL_FLAGS} ${PPCG_SCHEDULE_FLAGS} ${PPCG_OPENMP_FLAGS} $src_args -o ${target_file}.no-tile.c > /dev/null 2>&1
         # 临时加一个语句，生成只进行mix的版本
         ppcg --target c --no-automatic-mixed-precision --no-reschedule $src_args -o ${target_file}.only-mix.c > /dev/null 2>&1
     fi
+else
+    echo "lnlamp: error: There was a problem printing the final results, please contact the program developer! "
 fi
 echo ""
 
