增加了抛物线开口方向的判定,同时将profiling time的次数修改为了三次的平均值,且包含一次的数据预热.

diff --git a/lnlamp b/lnlamp
--- a/lnlamp
+++ b/lnlamp
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 # 获取lnlamp脚本所在的目录
 lnlamp_dir=$(cd `dirname $0`; pwd)
 # echo "lnlamp所在的路径是:" $lnlamp_dir
@@ -6,7 +7,6 @@ lnlamp_dir=$(cd `dirname $0`; pwd)
 Rootpath=`pwd`
 # echo "当前的工作路径是:" $Rootpath
 cd $Rootpath
-
 
 # 如果没有输入参数,直接退出,并提示用户lnlamp的用法
 if [ $# -eq 0 ];
@@ -64,6 +64,8 @@ function Solving_Equations(){
 
 
 
+# 调试模式开关
+DEBUG_TYPE=1
 # TODO: 添加计时方式 (-t|--timing-type) 的设置
 timing_type=0
 # TODO: 添加profiling时的输入文件 (-i|--input) 的设置
@@ -252,7 +254,9 @@ unset specify_output_flag
 
 #  Step2: 如果输入解析成功，那么开始进行Profiling
 time_array=()
-echo "lnlamp: message: Default Profiling Rate is: ${rate_array[0]} ${rate_array[1]} ${rate_array[2]}."
+if [ $DEBUG_TYPE -eq 1 ];then
+    echo "lnlamp: message: Default Profiling Rate is: ${rate_array[0]} ${rate_array[1]} ${rate_array[2]}."
+fi
 if [[ ${PARAMETER_READY} = true ]]; 
 then
     # PPCG Codegen
@@ -260,21 +264,25 @@ then
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: PPCG Codegen meets errors."
         echo "lnlamp: error: The PPCG CMD is : ppcg --target c --no-automatic-mixed-precision $src_args -o ____lnlamp_ppcg__${prf_suf} "
+        exit
     fi
     ppcg --target c -R ${rate_array[0]} $src_args -o ____lnlamp_${rate_array[0]}__${prf_suf} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: PPCG Codegen meets errors."
         echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${rate_array[0]} $src_args -o ____lnlamp_${rate_array[0]}__${prf_suf} "
+        exit
     fi
     ppcg --target c -R ${rate_array[1]} $src_args -o ____lnlamp_${rate_array[1]}__${prf_suf} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: PPCG Codegen meets errors."
         echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${rate_array[1]} $src_args -o ____lnlamp_${rate_array[1]}__${prf_suf} "
+        exit
     fi
     ppcg --target c -R ${rate_array[2]} $src_args -o ____lnlamp_${rate_array[2]}__${prf_suf} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: PPCG Codegen meets errors."
         echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R ${rate_array[2]} $src_args -o ____lnlamp_${rate_array[2]}__${prf_suf} "
+        exit
     fi
 
     # 编译
@@ -282,21 +290,25 @@ then
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: Compiling meets errors."
         echo "lnlamp: error: The compiler CMD is : ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_ppcg__${prf_suf} -o  ____lnlamp_ppcg__.exe ${EXIT_FLAGS}"
+        exit
     fi
     ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_${rate_array[0]}__${prf_suf} -o  ____lnlamp_${rate_array[0]}__.exe  ${EXIT_FLAGS}  > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: Compiling meets errors."
         echo "lnlamp: error: The compiler CMD is : ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_${rate_array[0]}__${prf_suf} -o  ____lnlamp_${rate_array[0]}__.exe  ${EXIT_FLAGS}"
+        exit
     fi
     ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_${rate_array[1]}__${prf_suf} -o  ____lnlamp_${rate_array[1]}__.exe  ${EXIT_FLAGS}  > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: Compiling meets errors."
         echo "lnlamp: error: The compiler CMD is : ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_${rate_array[1]}__${prf_suf} -o  ____lnlamp_${rate_array[1]}__.exe  ${EXIT_FLAGS}"
+        exit
     fi
     ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_${rate_array[2]}__${prf_suf} -o  ____lnlamp_${rate_array[2]}__.exe  ${EXIT_FLAGS} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: Compiling meets errors."
         echo "lnlamp: error: The compiler CMD is : ${VERBOSE} ${CC} ${CFLAGS} ${LIB_FLAGS} ${PROFILER_FLAGS} ____lnlamp_${rate_array[2]}__${prf_suf} -o  ____lnlamp_${rate_array[2]}__.exe  ${EXIT_FLAGS} "
+        exit
     fi
     # 删除PPCG CodeGen的源文件
     rm -f ____lnlamp_*__${prf_suf}
@@ -305,25 +317,78 @@ then
     if [ $timing_type -eq 1 ];
     then 
         timing="time -f %e"
-        echo "lnlamp: message: The Timing CMD is: '${timing}' ."
+        if [ $DEBUG_TYPE -eq 1 ];then
+            echo "lnlamp: message: The Timing CMD is: '${timing}' ."
+        fi
     else
         timing=""
     fi
 
     # Profiling (default input file is input.txt)
+    frequency=3
     if [ -e $input ];
     then
-        echo "lnlamp: message: Profiling will use the $input file ."
-        { ${timing} ./____lnlamp_ppcg__.exe             < $input > ____lnlamp_output_upper ; } 2> ____lnlamp_timing_upper
+        if [ $DEBUG_TYPE -eq 1 ];then
+            echo "lnlamp: message: Profiling will use the $input file ."
+        fi
+        { ${timing} ./____lnlamp_ppcg__.exe < $input > ____lnlamp_output_upper ; } 2> ____lnlamp_timing_upper
+        { ${timing} ./____lnlamp_ppcg__.exe < $input > ____lnlamp_output_upper ; } 2> ____lnlamp_timing_upper
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_ppcg__.exe < $input >> ____lnlamp_output_upper ; } 2>> ____lnlamp_timing_upper
+        done
+
         { ${timing} ./____lnlamp_${rate_array[0]}__.exe < $input > ____lnlamp_output_mix_0 ; } 2> ____lnlamp_timing_mix_0
+        { ${timing} ./____lnlamp_${rate_array[0]}__.exe < $input > ____lnlamp_output_mix_0 ; } 2> ____lnlamp_timing_mix_0
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_${rate_array[0]}__.exe < $input >> ____lnlamp_output_mix_0 ; } 2>> ____lnlamp_timing_mix_0
+        done
+
         { ${timing} ./____lnlamp_${rate_array[1]}__.exe < $input > ____lnlamp_output_mix_1 ; } 2> ____lnlamp_timing_mix_1
+        { ${timing} ./____lnlamp_${rate_array[1]}__.exe < $input > ____lnlamp_output_mix_1 ; } 2> ____lnlamp_timing_mix_1
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_${rate_array[1]}__.exe < $input >> ____lnlamp_output_mix_1 ; } 2>> ____lnlamp_timing_mix_1
+        done
+
         { ${timing} ./____lnlamp_${rate_array[2]}__.exe < $input > ____lnlamp_output_mix_2 ; } 2> ____lnlamp_timing_mix_2
+        { ${timing} ./____lnlamp_${rate_array[2]}__.exe < $input > ____lnlamp_output_mix_2 ; } 2> ____lnlamp_timing_mix_2
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_${rate_array[2]}__.exe < $input >> ____lnlamp_output_mix_2 ; } 2>> ____lnlamp_timing_mix_2
+        done
     else
-        echo "lnlamp: message: Profiling will not use any input file(which means the program does not require any input)."
-        { ${timing} ./____lnlamp_ppcg__.exe             > ____lnlamp_output_upper ; } 2> ____lnlamp_timing_upper
+        if [ $DEBUG_TYPE -eq 1 ];then
+            echo "lnlamp: message: Profiling will not use any input file(which means the program does not require any input)."
+        fi
+        { ${timing} ./____lnlamp_ppcg__.exe > ____lnlamp_output_upper ; } 2> ____lnlamp_timing_upper
+        { ${timing} ./____lnlamp_ppcg__.exe > ____lnlamp_output_upper ; } 2> ____lnlamp_timing_upper
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_ppcg__.exe >> ____lnlamp_output_upper ; } 2>> ____lnlamp_timing_upper
+        done
+
         { ${timing} ./____lnlamp_${rate_array[0]}__.exe > ____lnlamp_output_mix_0 ; } 2> ____lnlamp_timing_mix_0
+        { ${timing} ./____lnlamp_${rate_array[0]}__.exe > ____lnlamp_output_mix_0 ; } 2> ____lnlamp_timing_mix_0
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_${rate_array[0]}__.exe >> ____lnlamp_output_mix_0 ; } 2>> ____lnlamp_timing_mix_0
+        done
+
         { ${timing} ./____lnlamp_${rate_array[1]}__.exe > ____lnlamp_output_mix_1 ; } 2> ____lnlamp_timing_mix_1
+        { ${timing} ./____lnlamp_${rate_array[1]}__.exe > ____lnlamp_output_mix_1 ; } 2> ____lnlamp_timing_mix_1
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_${rate_array[1]}__.exe >> ____lnlamp_output_mix_1 ; } 2>> ____lnlamp_timing_mix_1
+        done
+
         { ${timing} ./____lnlamp_${rate_array[2]}__.exe > ____lnlamp_output_mix_2 ; } 2> ____lnlamp_timing_mix_2
+        { ${timing} ./____lnlamp_${rate_array[2]}__.exe > ____lnlamp_output_mix_2 ; } 2> ____lnlamp_timing_mix_2
+        for ((i=1; i<$frequency; i++))
+        do
+            { ${timing} ./____lnlamp_${rate_array[2]}__.exe >> ____lnlamp_output_mix_2 ; } 2>> ____lnlamp_timing_mix_2
+        done
     fi
     # 删除程序的可执行文件
     rm -f ____lnlamp_*_.exe
@@ -333,70 +398,181 @@ then
     then
         # 说明程序的输出不是计时结果,删除____lnlamp_output_*
         rm -f ____lnlamp_output_*
-        time_upper=`head -1 ____lnlamp_timing_upper | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
-        time_mix_0=`head -1 ____lnlamp_timing_mix_0 | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
-        time_mix_1=`head -1 ____lnlamp_timing_mix_1 | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
-        time_mix_2=`head -1 ____lnlamp_timing_mix_2 | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
+        rows=$(awk 'END{print NR}' ____lnlamp_timing_upper);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_timing_upper;
+            time_upper=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
+        rows=$(awk 'END{print NR}' ____lnlamp_timing_mix_0);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_timing_mix_0;
+            time_mix_0=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
+        rows=$(awk 'END{print NR}' ____lnlamp_timing_mix_1);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_timing_mix_1;
+            time_mix_1=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
+        rows=$(awk 'END{print NR}' ____lnlamp_timing_mix_2);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_timing_mix_2;
+            time_mix_2=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
 
         # 删除程序的计时结果文件
         rm -f ____lnlamp_timing_*
     else
         # 说明程序的输出是计时结果，则删除____lnlamp_timing_*
         rm -f ____lnlamp_timing_*
-        time_upper=`head -1 ____lnlamp_output_upper | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
-        time_mix_0=`head -1 ____lnlamp_output_mix_0 | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
-        time_mix_1=`head -1 ____lnlamp_output_mix_1 | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
-        time_mix_2=`head -1 ____lnlamp_output_mix_2 | sed -ne 's/[^0-9]*\([0-9]*\.[0-9]*\)[^0-9]*/\1/p'`
+        rows=$(awk 'END{print NR}' ____lnlamp_output_upper);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_output_upper;
+            time_upper=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
+        rows=$(awk 'END{print NR}' ____lnlamp_output_mix_0);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_output_mix_0;
+            time_mix_0=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
+        rows=$(awk 'END{print NR}' ____lnlamp_output_mix_1);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_output_mix_1;
+            time_mix_1=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
+        rows=$(awk 'END{print NR}' ____lnlamp_output_mix_2);
+        if [ $frequency -eq $rows ];
+        then 
+            expr=0.0;
+            while read n; 
+            do
+                expr=$(echo $expr $n | awk '{ printf("%.10f",$1+$2); }');
+            done < ____lnlamp_output_mix_2;
+            time_mix_2=$(echo $expr $frequency | awk '{ printf("%.10f",$1/$2); }');
+        else
+            echo "lnlamp: error: Parsing profile time meets errors."
+            exit
+        fi
 
         # 删除程序的计时结果文件
         rm -f ____lnlamp_output_*
     fi
-    echo "lnlamp: message: Profiling times is: $time_upper $time_mix_0 $time_mix_1 $time_mix_2"
+    if [ $DEBUG_TYPE -eq 1 ];then
+        echo "lnlamp: message: Profiling times is: $time_upper $time_mix_0 $time_mix_1 $time_mix_2"
+    fi
     time_array+=( $(echo $time_upper $time_mix_0 | awk '{ printf("%.10f", $1-$2 ); }') );
     time_array+=( $(echo $time_upper $time_mix_1 | awk '{ printf("%.10f", $1-$2 ); }') );
     time_array+=( $(echo $time_upper $time_mix_2 | awk '{ printf("%.10f", $1-$2 ); }') );
 
     # 解方程组,求解抛物线的三个参数
-    Solving_Equations ${rate_array[0]} ${time_array[0]}  ${rate_array[1]}  ${time_array[1]}  ${rate_array[2]}  ${time_array[2]}
+    Solving_Equations ${rate_array[0]} ${time_array[0]} ${rate_array[1]} ${time_array[1]} ${rate_array[2]} ${time_array[2]}
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: Solving_Equations meets errors"
-        echo "lnlamp: Solving_Equations Parameter is: ${rate_array[0]} ${time_array[0]}  ${rate_array[1]}  ${time_array[1]}  ${rate_array[2]}  ${time_array[2]} "
+        echo "lnlamp: Solving_Equations Parameter is: ${rate_array[0]} ${time_array[0]} ${rate_array[1]} ${time_array[1]} ${rate_array[2]} ${time_array[2]}"
         echo "lnlamp: The wrong result is: $equ_a $equ_b $equ_c $extremeValue"
+        exit
     fi
-    # echo "lnlamp: Solving_Equations Parameter is: ${rate_array[0]} ${time_array[0]}  ${rate_array[1]}  ${time_array[1]}  ${rate_array[2]}  ${time_array[2]} "
-    echo "lnlamp: message: Solving equations's Result is: $equ_a $equ_b $equ_c $extremeValue"
+    if [ $DEBUG_TYPE -eq 1 ];then
+        echo "lnlamp: message: Solving_Equations Parameter is: ${rate_array[0]} ${time_array[0]} ${rate_array[1]} ${time_array[1]} ${rate_array[2]} ${time_array[2]}"
+        echo "lnlamp: message: Solving equations's Result is: ( pi(r) = $equ_a * r^2 + $equ_b * r + $equ_c, the extreme value point is located at r = $extremeValue ) "
+        echo ""
+    fi
 fi
 
 
 
 # Step3: 根据抛物线和Profiling结果,分类并生成最终结果.
-if [ $(echo "$extremeValue < 0" | bc) -eq 1 ];
+# 如果开口向下且对称轴小于0、或者开头向上且对称轴大于99,那么就是收益模型单调下降.
+if ([ $(echo "$extremeValue < 0" | bc) -eq 1 ] && [ $(echo "$equ_a < 0" | bc) -eq 1 ]) || ([ $(echo "$extremeValue > 99" | bc) -eq 1 ] && [ $(echo "$equ_a > 0" | bc) -eq 1 ]);
 then
     ppcg --target c -R 0 $src_args -o ${target_file} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: PPCG Codegen(Rate=0) meets errors."
         echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R 0 $src_args -o ${target_file}."
+        exit
     fi
-    echo ""
     echo "The performance of lnlamp programs decreases monotonically with increasing Rate, so the Rate 0 is the best. "
     echo "We have automatically generated a mixed precision program (${target_file})at this Ratio. "
     echo ""
-elif [ $(echo "$extremeValue > 99" | bc) -eq 1 ];
+# 如果开口向下且对称轴大于99、或者开头向上且对称轴小于0,那么就是收益模型单调上升.
+elif ([ $(echo "$extremeValue > 99" | bc) -eq 1 ] && [ $(echo "$equ_a < 0" | bc) -eq 1 ]) || ([ $(echo "$extremeValue < 0" | bc) -eq 1 ] && [ $(echo "$equ_a > 0" | bc) -eq 1 ]);
 then
-    echo ""
-    echo "The performance of the lnlamp program rises monotonically with increasing Rate, so the orgion program is best. "
+    echo "The performance of the lnlamp program rises monotonically with increasing Rate, so the original program is probably the best. "
     echo "The program is not suitable for mixed precision optimization at the loop nesting level. "
     echo ""
-else
+# 如果对称轴介于0和99中间，且开头是向下的话,那么对称轴附近的比例值就是结果
+elif [ $(echo "$equ_a < 0" | bc) -eq 1 ];
+then
     final_rate=$(echo $extremeValue | cut -d '.' -f1);
     ppcg --target c -R $final_rate $src_args -o ${target_file} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "lnlamp: error: PPCG Codegen(Final-rate=$final_rate) meets errors."
         echo "lnlamp: error: The PPCG CMD is : ppcg --target c -R $final_rate $src_args -o ${target_file}."
+        exit
     fi
-    echo ""
     echo "The performance of the lnlamp program shows a quadratic relationship with the Rate ( pi(r) = $equ_a * r^2 + $equ_b * r + $equ_c )."
     echo "So the integer value around Rate ($extremeValue) is probably the most appropriate ratio. "
     echo "We have automatically generated a mixed precision program (${target_file}) at the Rate=$final_rate. "
+    echo ""
+# 如果对称轴介于0和99中间，且开头是向上的话，那么同样也不适合做混合精度.
+else
+    echo "The performance of the lnlamp program shows a quadratic relationship with the Rate ( pi(r) = $equ_a * r^2 + $equ_b * r + $equ_c )."
+    echo "Unfortunately, we did not find the most suitable mixed precision Rate for this program. "
+    echo "We recommend that you could use our modified ppcg code auto-generation tool to assist you in mixing precision optimization."
     echo ""
 fi
